scaffold_name: static_math_agent
core_components: configs/agents/math_core_components.yaml
n_threads: 8
max_concurrent_calls: 8
n_approach_solutions: 0
n_no_approach_solutions: 4
merge_solutions: true
use_no_approach: true
n_solutions_per_approach: 2
n_verifications_per_solution: 1
run_idx: '{solver_path}/math_static_agent_{parameter_hash}_{problem_id}_{run_idx}'
