type: agent
model_config: models/vllm/vllm-lm-provers-qwen3-4b-thinking-2507-sft
scaffold_config: agents/reasoning_cache
human_readable_id: "lm-provers/Qwen3-4B-Thinking-2507-SFT + reasoning_cache (v08.00-step-000000124)"
