model: gemini-3-flash-preview
api: google
temperature: null
top_p: null
concurrent_requests: 32
max_tokens: 64000
read_cost: 0.5
tool_choice: auto
write_cost: 3
extra_body:
  extra_body:
    google:
      thinking_config:
        include_thoughts: true
        thinking_level: minimal
