type: agent
model_config: models/vllm/vllm-lm-provers-qwen3-4b-thinking-2507-proof
scaffold_config: agents/reasoning_cache_with_instructions
human_readable_id: "lm-provers/Qwen3-4B-Thinking-2507-Proof + reasoning_cache_with_instructions (rc_v07.00-step-000150)"
